version: "3"
services:
  mongo:
    container_name: trello-clone-mongo
    image: mongo
    ports:
      - "27017:27017"
  redis:
    container_name: trello-clone-redis
    image: redis
    ports:
      - "6379:6379"
